In [ ]:
items = [1, 2.0, True, "Hello", [1,2]]

In [ ]:
import numpy as np

In [ ]:
fruits = ['apple','orange','pineapple']
fruits_array = np.array(fruits)
print(fruits_array)


In [ ]:
items = [1,"Hello",True]
print(np.array(items))


In [ ]:
['1' 'Hello' 'True']

In [ ]:
items = [1, 0, True, False]
print(np.array(items))
# [1 0 1 0]

items = [1, 3.0 ,True]
print(np.array(items))
# [1. 3. 1.]


In [ ]:
print(fruits_array.shape)

In [ ]:
print(fruits_array.size)     # 3

In [ ]:
print(fruits_array[0])

In [ ]:
print(fruits_array[-1])     # pineapple

In [ ]:
print(fruits_array[[2,0,1]])
# ['pineapple' 'apple' 'orange']


In [ ]:
fruits[:2]      # first 2 elements
# ['apple', 'orange']

fruits[1:]      # second element onwards
# ['orange', 'pineapple']

fruits[::-1]    # get all elements in reverse
# ['pineapple', 'orange', 'apple']


In [ ]:
array1 = np.array([[1,2,3,4,5], 
                   [4,5,6,7,8], 
                   [9,8,7,6,5]])
print(array1)


In [ ]:
print(array1.shape)
# (3, 5) – the output is in the format of (row, column)


In [ ]:
print(array1.size)
# 15


In [ ]:
print(array1[2,4])   # third row, fifth column
# 5


In [ ]:
a = array1[:2,2:4]   # first 2 rows, third to fourth columns
print(a)


In [ ]:
a[0,0] = 33    # remember a is a reference to the original array
print(array1)


In [ ]:
nums = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])


In [ ]:
nums % 2 == 0

In [ ]:
print(nums[nums % 2 == 0])
# [2 4 6 8]


In [ ]:
print(nums[nums>5])
# [6 7 8 9]  - all numbers greater than 5

print(nums[nums%2==1])
# [1 3 5 7 9] - all odd numbers

print(nums[nums%3==0])
# [3 6 9] - all numbers divisible by 3

print(nums[(nums>3) & (nums<6)])
# [4 5] - all numbers greater than 3 AND smaller than 6

print(nums[(nums<3) | (nums>6)])
# [1 2 7 8 9] all numbers smaller than 3 OR greater than 6

print(nums[~(nums==5)])
# [1 2 3 4 6 7 8 9] all numbers except 5


In [ ]:
nums = np.array([1,2,3,4,5,6,7,8])

In [ ]:
print(nums.reshape((2,4)))

In [ ]:
print(nums.reshape((2,2,2)))

In [ ]:
print(nums.reshape(4,-1))

In [ ]:
nums.reshape(-1,4)

In [ ]:
items         = np.array(['Milk','Eggs','Pasta','Potatoes','Cheese'])
unit_prices   = np.array([3.49, 1.99, 1.19, 0.69, 2.79])
cost_per_unit = np.array([2.59, 1.00, 0.70, 0.25, 2.01])
qty_sold      = np.array([100,500,50,340,60])


In [ ]:
total_sales = unit_prices * qty_sold
# array([349. , 995. ,  59.5, 234.6, 167.4])

total_cost = cost_per_unit * qty_sold
# array([259. , 500. ,  35. ,  85. , 120.6])

total_profit = total_sales - total_cost
# array([ 90. , 495. ,  24.5, 149.6,  46.8])


In [ ]:
print(f'Total Sales: ${np.sum(total_sales):.2f}')
print(f'Total Cost ${np.sum(total_cost):.2f}')
print(f'Total Profit ${np.sum(total_profit):.2f}')


In [ ]:
profit_per_unit = unit_prices - cost_per_unit
# array([0.9 , 0.99, 0.49, 0.44, 0.78])


In [ ]:
np.argsort(profit_per_unit)
# array([3, 2, 4, 0, 1])


In [ ]:
items[np.argsort(profit_per_unit)]
# array(['Potatoes', 'Pasta', 'Cheese', 'Milk', 'Eggs'], dtype='<U8')


In [ ]:
items[np.argsort(profit_per_unit)[::-1]]
# array(['Eggs', 'Milk', 'Cheese', 'Pasta', 'Potatoes'], dtype='<U8')


In [ ]:
persons = np.array(['Emma','Liam','Olivia','Noah','Ava'])
ages    = np.array([    32,    10,      39,     6,  10])
heights = np.array([   182,   145,     172,   112, 143])


In [ ]:
np.lexsort((ages,heights))
# array([3, 4, 1, 2, 0])


In [ ]:
persons[np.lexsort((ages,heights))]
# array(['Noah', 'Ava', 'Liam', 'Olivia', 'Emma'], dtype='<U6')


In [ ]:
arr1 = np.array([45,23,78,21,79,86])

In [ ]:
np.where(arr1 % 2 == 0)

In [ ]:
print(arr1[np.where(arr1 % 2 == 0)])
# [78 86]


In [ ]:
np.where(arr1 % 2 == 0, 'Even', 'Odd')
# array(['Odd', 'Odd', 'Even', 'Odd', 'Odd', 'Even'], dtype='<U4')


In [ ]:
import pandas as pd

In [ ]:
fruits = pd.Series(['Apple','Orange','Pineapple','Durian','Mango'])
print(fruits)


In [ ]:
fruits.index
# RangeIndex(start=0, stop=5, step=1)


In [ ]:
fruits[0]         # find element by index value 0
# 'Apple'


In [ ]:
fruits.loc[0]

In [ ]:
fruits.loc[0:3]

In [ ]:
fruits.index = ['a','o','p','d','m']
print(fruits)


In [ ]:
fruits['a']
# OR
fruits.loc['a']
# 'Apple'


In [ ]:
fruits['o':'p']

In [ ]:
fruits.isin(['Pineapple'])

In [ ]:
fruits[fruits.isin(['Pineapple'])]

In [ ]:
fruits[fruits.isin(['Pineapple','Orange'])]

In [ ]:
fruits[fruits.str.contains('apple', case = False)]

In [ ]:
fruits.iloc[1]    # second row
# 'Orange'
fruits.iloc[-2]
# 'Durian'        # second last row


In [ ]:
fruits.iloc[:3]

In [ ]:
dates1 = pd.date_range('2023.12.05', periods=12, freq='D')
list(dates1)


In [ ]:
dates2 = pd.date_range('2023-12-01', periods=12, freq='MS')
list(dates2)


In [ ]:
dates3 = pd.date_range('2023/12/15 09:00:00', periods=8, freq='H')
list(dates3)


In [ ]:
temperature = pd.Series([30.0,31.4,32.8,31.5,29,28.5,30,33])

In [ ]:
temperature.index = pd.date_range('2023/12/15 09:00:00', periods=8, freq='H')

In [ ]:
df = pd.DataFrame(
    {
        'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 28],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
    }
)
df


In [ ]:
df = pd.read_csv('airports.csv')
df


In [ ]:
df.shape

In [ ]:
df.dtypes

In [ ]:
df.columns

In [ ]:
print(df.values)

In [ ]:
df.head()      # returns the first five rows

In [ ]:
df.head(10)    # returns the first ten rows

In [ ]:
df.tail()      # returns the last five rows
df.tail(8)     # returns the last right rows


In [ ]:
df.sample()    # randomly returns one row
df.sample(5)   # randomly returns five rows


In [ ]:
df['IATA_CODE']

In [ ]:
df[['IATA_CODE']]

In [ ]:
df[['IATA_CODE','AIRPORT']]

In [ ]:
df.iloc[0]

In [ ]:
df.iloc[[0]]

In [ ]:
df.iloc[0:2]    # row number 0 to 2 (not including 2)

In [ ]:
df.loc[0:2]     # row with index value 0 to 2 (2 inclusive)

In [ ]:
df[df['STATE'] == 'PA']

In [ ]:
df[df['AIRPORT'].str.contains('International')]

In [ ]:
df[(df['AIRPORT'].str.contains('International')) |
   (df['AIRPORT'].str.contains('Regional'))]


In [ ]:
df.query('STATE == "PA"')
df.query('AIRPORT.str.contains("International")')
df.query('AIRPORT.str.contains("International") or  AIRPORT.str.contains("Regional")')


In [ ]:
df.iloc[2,3]
df.iloc[1:3,2:4]
df.iloc[[1,2],[2,3]]
df.loc[0,'AIRPORT']
df.loc[1:3,'AIRPORT':'CITY']
df.loc[[1,3],['AIRPORT','CITY']]


In [ ]:
df = pd.DataFrame(
    {
        'x': [1,2,3,4,5],
        'y': [6,7,8,9,10]
    })
df


In [ ]:
def double(x):
    return x * 2


In [ ]:
df.apply(double)

In [ ]:
def double(x):
    print(f'Value of x is:')
    print(x)
    return x * 2 


In [ ]:
df.apply(double, axis=1)

In [ ]:
df = pd.DataFrame(
    {
        'Items': ['Milk','Eggs','Pasta','Potatoes','Cheese'],
        'Price': [3.49, 1.99, 1.19, 0.69, 2.79]
    })


In [ ]:
def apply_tax(x):
    return round(x * 1.08, 2)

df['Price_with_tax'] = df['Price'].apply(apply_tax)
df
